//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sharipov
{
    using System;
    using System.Collections.Generic;
    using System.Windows;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Orders = new HashSet<Order>();
        }
        public string NewCost
        {
            get
            {
                if (ProductDiscountAmount > 0)
                {
                    decimal newcost = (decimal)(ProductCost - (ProductCost / 100 * ProductDiscountAmount));
                    return newcost.ToString();
                }
                return ((decimal)ProductCost).ToString();
            }
        }
        public string OldCost
        {
            get
            {
                if (ProductDiscountAmount > 0)
                {
                    return ProductCost.ToString();
                }
                return "";
            }
        }
        public Visibility Vis
        {
            get
            {
                if (UserID.ID == 2)
                    return Visibility.Visible;
                else
                    return Visibility.Collapsed;

            }
        }

        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductUnit { get; set; }
        public decimal ProductCost { get; set; }
        public int ProductDiscountMax { get; set; }
        public string ProductManufacturer { get; set; }
        public string ProductProvider { get; set; }
        public string ProductCategory { get; set; }
        public Nullable<byte> ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductDescription { get; set; }
        public string ProductPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
